#!/bin/zsh


set -u
set -o pipefail

readonly CLRLINE='\033[0K'
readonly ESC='\033[0m'
readonly BOLD='\033[1m'
readonly BLUE='\033[34m'
readonly BLUE_UL='\033[4;34m'
readonly GREEN='\033[32m'
readonly GREEN_UL='\033[4;32m'
readonly RED='\033[31m'

# Script to perform installation of Nix on MacOS
#

{ # Prevent execution if this script was only partially downloaded

function get_gitfolder () {
    [[ ! -n "${gitfolder+1}" ]] || return
    local prompt="${BOLD}${GREEN}Enter name of subfolder within $HOME to clone mymacnix: ${ESC}"
    printf "$prompt"
    while read -r folder </dev/tty; do
        if [ "$folder" != "" ]; then
            if [[ ! -e "$HOME/$folder" ]]; then
                break
            fi
            echo "${RED}$HOME/$folder already exists - please choose another directory${ESC}"
        fi
        printf "$prompt"
    done
    eval "export gitfolder=$HOME/$folder"
}

get_gitfolder

## Executed the startup scripts to ensure nix path is present
if [[ ! $(nix --version) ]]; then
    . /etc/zprofile
    . /etc/zshrc
fi

mkdir -p ~/.config

nix-shell -p git stow --command '
git clone --recurse-submodules https://github.com/khsoh/mymacnix.git "$gitfolder"
cd "$gitfolder"
stow -Rt ~ HOME
'

echo "${BOLD}${GREEN}--> Starting a new sub-shell to install nix-darwin${ESC}"
pushd "$gitfolder"
zsh -l darwin-autoinstall
popd

} # End of wrapping

