#!/bin/zsh


set -u
set -o pipefail

readonly CLRLINE='\033[0K'
readonly ESC='\033[0m'
readonly BOLD='\033[1m'
readonly BLUE='\033[34m'
readonly BLUE_UL='\033[4;34m'
readonly GREEN='\033[32m'
readonly GREEN_UL='\033[4;32m'
readonly RED='\033[31m'

# Script to clone the mymacnix repo, stow the HOME subfolder in the repo and
# install and configure nix-darwin

{ # Prevent execution if this script was only partially downloaded

function print_arrow () {
    printf "${BOLD}${GREEN}"
    printf "=%.0s" {1..$SHLVL} 
    printf "> "
    printf "$1${ESC}\n"
}

function get_gitfolder () {
    [[ ! -n "${gitfolder+1}" ]] || return
    local prompt="${BOLD}${GREEN}Enter name of subfolder within $HOME to clone mymacnix: ${ESC}"
    printf "$prompt"
    while read -r folder </dev/tty; do
        if [ "$folder" != "" ]; then
            if [[ ! -e "$HOME/$folder" ]]; then
                break
            fi
            printf "${RED}$HOME/$folder already exists - please choose another directory${ESC}\n"
        fi
        printf "$prompt"
    done
    eval "export gitfolder=$HOME/$folder"
}

## Test to confirm nix has been installed
if [[ ! $(mount | grep -w "/nix") ]]; then
    printf "${BOLD}${RED}Error: Nix has not yet been installed - clonerepo-autoinstall script cannot be executed${ESC}\n"
    exit 1
fi

## Executed the startup scripts to ensure nix path is present
if [[ ! $(nix --version 2>/dev/null) ]]; then
    . /etc/zprofile
    . /etc/zshrc
fi

if [[ $(darwin-version --version 2>/dev/null) ]]; then
    printf "${BOLD}${RED}nix-darwin already installed - will not clone mymacnix repo to install nix-darwin${ESC}\n"
    exit 1
fi

get_gitfolder

mkdir -p ~/.config

print_arrow "Cloning mymacnix repo"
nix-shell -p git stow --command '
git clone --recurse-submodules https://github.com/khsoh/mymacnix.git "$gitfolder"
bash -l "$gitfolder/dostow.sh"
'

print_arrow "Starting a new sub-shell to install nix-darwin"
pushd "$gitfolder"
zsh -l darwin-autoinstall
popd

} # End of wrapping

