#!/bin/sh


set -u
set -o pipefail

readonly CLRLINE='\033[0K'
readonly ESC='\033[0m'
readonly BOLD='\033[1m'
readonly BLUE='\033[34m'
readonly BLUE_UL='\033[4;34m'
readonly GREEN='\033[32m'
readonly GREEN_UL='\033[4;32m'
readonly RED='\033[31m'

# Script to perform installation of nix-darwin on MacOS
#

{ # Prevent execution if this script was only partially downloaded
umask 0022

nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
yes | ./result/bin/darwin-installer

echo -e "${BOLD}{$GREEN}Start a new Terminal to start using nix-darwin"

} # End of wrapping

