#!/usr/bin/env bash

_USERINFO=$(cat <<EOF
## This file is autogenerated - DO NOT EDIT
{
  name = "$(id -un)";
  home = "$HOME";
  uid = $(id -u);
  hasAppleID = $(defaults read MobileMeAccounts Accounts >/dev/null 2>&1 && echo "true" || echo "false");
}
# vim: set ts=2 sw=2 et ft=nix:
EOF
)
_USERNIX=~/.config/nixpkgs/darwin/_user.nix

if [[ -f $_USERNIX ]] && diff $_USERNIX <(echo "$_USERINFO") >/dev/null ; then
    exit 0
fi

echo "Auto-generating $_USERNIX file"
echo "$_USERINFO" > $_USERNIX
