#!/usr/bin/env bash

_USERINFO=$(cat <<EOF
## This file is autogenerated - DO NOT EDIT
{
  name = "$(id -un)";
  home = "$(python -c 'import os; print(os.path.expanduser("~"))')";
  uid = $(id -u);
}
# vim: set ts=2 sw=2 et ft=nix:
EOF
)
_USERNIX=~/.config/nixpkgs/darwin/_user.nix
echo "in genusernix.sh"
if [ ! -d ~/.config ]; then
  echo "~/.config does not exist"
elif [ ! -d ~/.config/nixpkgs ]; then
  echo "~/.config/nixpkgs does not exist"
elif [ ! -d ~/.config/nixpkgs/darwin ]; then
  echo "~/.config/nixpkgs/darwin does not exist"
elif [ ! -e ~/.config/nixpkgs/darwin/_user.nix ]; then
  echo "~/.config/nixpkgs/darwin/_user.nix does not exist"
fi

if [[ -f $_USERNIX ]]; then
  echo have "$_USERNIX"
fi
if [[ -f $_USERNIX ]] && diff $_USERNIX <(echo "$_USERINFO") >/dev/null ; then
    exit 0
fi

echo "Auto-generating $_USERNIX file"
echo "$_USERINFO" > $_USERNIX
