#!/bin/zsh


set -u
set -o pipefail

## Choice of repository host "github" or "gitlab"

REPOHOST=gitlab

readonly ESC="$(tput sgr0)"
readonly BOLD="$(tput bold)"
readonly GREEN="$(tput setaf 2)"
readonly RED="$(tput setaf 1)"

SCRIPTNAME=$(readlink -f "$0")
SCRIPTDIR=$(dirname "$SCRIPTNAME")

# Script to clone the mymacnix repo, stow the HOME subfolder in the repo and
# install and configure nix-darwin

function print_arrow () {
    printf "${BOLD}${GREEN}"
    eval $(echo printf '"=%.0s"' {1..$SHLVL})
    printf "> $*${ESC}\n"
}

function usage () {
    print_arrow "Usage: "
    print_arrow "  zsh -l nixsys-setup [--install=nixonly] [--branch=<feature-branch>] [--repohost=(gitlab|github)]"
    print_arrow "    The default feature-branch is 'main' if it is not specified"
    print_arrow "    The default repohost is 'gitlab' if it is not specified"
    exit 1
}

function get_gitfolder () {
    [[ ! -n "${gitfolder+1}" ]] || return
    local prompt="${BOLD}${GREEN}Enter name of subfolder within $HOME to clone mymacnix: ${ESC}"
    printf "$prompt"
    while read -r folder </dev/tty; do
        if [ "$folder" != "" ]; then
            if [[ ! -e "$HOME/$folder" ]]; then
                break
            fi
            printf "${RED}$HOME/$folder already exists - please choose another directory${ESC}\n"
        fi
        printf "$prompt"
    done
    eval "export gitfolder=$HOME/$folder"
}

## Test to confirm nix has been installed
if [[ ! $(/sbin/mount | grep -w "/nix") ]]; then
    printf "${BOLD}${RED}Error: Nix has not yet been installed - nixsys-setup script cannot be executed${ESC}\n"
    exit 1
fi

OPTINSTALL="all"
BRANCH="main"
CMDARGS=( "$@" )
while test $# -gt 0; do
    case "$1" in
        --install=nixonly)
            OPTINSTALL="${1##--install=}";;
        --branch=*)
            BRANCH="${1##--branch=}";;
        --repohost=*)
            REPOHOST="${1##--repohost=}";;
        *)
            echo "Invalid option $1"
            usage;;
    esac
    shift
done

## Executed the startup scripts to check what whether nix or nix-darwin installed
DARWININSTALLED=1
ZSCRIPTSRUN=0

if [[ ! $(nix --version 2>/dev/null) ]]; then
    ## Executed the startup scripts to ensure nix path is present
    [[ -f /etc/zshenv ]] && . /etc/zshenv
    [[ -f /etc/zprofile ]] && . /etc/zprofile
    [[ -f /etc/zshrc ]] && . /etc/zshrc
    ZSCRIPTSRUN=1
    if [[ ! $(nix --version 2>/dev/null) ]]; then
        printf "${BOLD}${RED}nix cannot be executed even after executing /etc/z* startup scripts - something is wrong with this setup${ESC}\n"
        exit 1
    fi
fi

if [[ ! $(darwin-version --version 2>/dev/null) ]]; then
    if [[ ZSCRIPTSRUN -eq 1 ]]; then
        DARWININSTALLED=0
    else
        [[ -f /etc/zshenv ]] && . /etc/zshenv
        [[ -f /etc/zprofile ]] && . /etc/zprofile
        [[ -f /etc/zshrc ]] && . /etc/zshrc
        if [[ ! $(darwin-version --version 2>/dev/null) ]]; then
            DARWININSTALLED=0
        fi
    fi
fi

# Define where the config is
NIX_DARWIN_DIR="/etc/nix-darwin"
SCRIPT_PATH="$NIX_DARWIN_DIR/generate_machine_info.sh"
MINFO_FILE="$NIX_DARWIN_DIR/machine-info.nix"

if [ ! -f $SCRIPT_PATH ]; then
    # 1. Ensure the directory exists
    sudo mkdir -p "$NIX_DARWIN_DIR"

    # 2. Write the script to the disk
    sudo -H tee "$SCRIPT_PATH" > /dev/null <<'EOF'
#!/usr/bin/env bash
IS_VM=$(/usr/sbin/sysctl -n kern.hv_vmm_present)
XHOSTNAME=$(/usr/sbin/scutil --get LocalHostName)
BGROUPID=$(dscl . -read /Groups/nixbld PrimaryGroupID 2>/dev/null | awk '{ print $2 }')
if [ -z "$BGROUPID" ]; then
  BGROUPID=350
fi
MINFO_FILE="$1"
cat <<EOF2 > "$MINFO_FILE"
{
  is_vm = $IS_VM;
  hostname = "${XHOSTNAME}";
  buildGroupID = $BGROUPID;
}
EOF2
EOF

    # 3. Make the script executable
    sudo -H chmod +x "$SCRIPT_PATH"

    # 4. Run the script *now* to create the initial machine-info.nix file
    sudo -H "$SCRIPT_PATH" "$MINFO_FILE"
fi

if [[ $DARWININSTALLED -eq 1 ]]; then
    printf "${BOLD}${RED}nix-darwin already installed - re-running darwin-rebuild switch${ESC}\n"
    sudo -H darwin-rebuild switch
    exit
fi

# Added code to install Xcode command line tools
print_arrow "Checking whether Xcode command line tools have been installed"
sudo -H xcode-select -p &> /dev/null
if [ $? -ne 0 ]; then
  print_arrow "Command Line Tools for Xcode not found. Installing from softwareupdate…"
# This temporary file prompts the 'softwareupdate' utility to list the Command Line Tools
  touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
  PROD=$(softwareupdate -l | grep "\*.*Command Line" | tail -n 1 | sed 's/^[^C]* //')
  softwareupdate -i "$PROD" --verbose;
else
  print_arrow "Command Line Tools for Xcode have been installed."
fi


git -C "$SCRIPTDIR" rev-parse 2>/dev/null
if [ $? -ne 0 ]; then
    ## Script folder is not a git folder
    get_gitfolder

    mkdir -p ~/.config/git

    print_arrow "Cloning branch ${BRANCH} of mymacnix repo"
    export BRANCH
    export REPOHOST
    [ -f /etc/zshenv ] && . /etc/zshenv
    [ -f /etc/zprofile ] && . /etc/zprofile
    [ -f /etc/zshrc ] && . /etc/zshrc
    nix-shell -p git stow openssh --command '
    echo "Cloning branch ${BRANCH} from ${REPOHOST}"
    git clone --branch ${BRANCH} --recurse-submodules https://${REPOHOST}.com/khsoh/mymacnix.git "$gitfolder"
    mkdir -p ~/Library/LaunchAgents
    cd $gitfolder
    ./git-remote-init.sh
    source "$gitfolder/dostow.sh"
    cd ..

    killall ssh-agent
    if [ -e ~/.ssh/nixid_ed25519 ]; then
        eval $(ssh-agent)
        ssh-add ~/.ssh/nixid_ed25519
    elif [ -e ~/.ssh/id_ed25519 ]; then
        eval $(ssh-agent)
        ssh-add ~/.ssh/id_ed25519
    else
        echo "=================================="
        echo "Preparing to use hardware security token to clone a private repo from ${REPOHOST}.com"
        echo "=================================="
        aptmpdir="$(mktemp -d -t aptmpdir.XXXXXX)"
        read -n 1 -s -r -p "Plug in your security token then press any key to continue..."
        git clone https://github.com/theseal/ssh-askpass.git "$aptmpdir"
        export SSH_ASKPASS=$aptmpdir/ssh-askpass
        eval $(ssh-agent)
        ssh-add -K
    fi
    git clone git@${REPOHOST}.com:khsoh/caskmasapps.git
    if [ ! -z ${aptmpdir+x} ]; then
        rm -rf $aptmpdir
    fi

    cd caskmasapps
    ./dostow.sh
    '

    print_arrow "Completed cloning the repository"
else
    gitfolder=$SCRIPTDIR
fi

NEWCMDARGS=${CMDARGS[@]//--install=*/}
if [[ $OPTINSTALL == "nixonly" ]]; then
    print_arrow "Completed installing only nix and cloning repo"
    print_arrow "To proceed, open a new terminal and execute:"
    print_arrow "   cd \"$gitfolder\""
    print_arrow "   zsh -l nixsys-setup $NEWCMDARGS"
    exit
fi

## Generate the primary user nix file
if [ ! -e ~/.config/nixpkgs/darwin/user.nix ]; then
    $SCRIPTDIR/genusernix.sh
fi

## Update the nix channels
sudo -H nix-channel --update

print_arrow "Installing nix-darwin"
cd "$gitfolder"
zsh -l scripts/darwin-autoinstall


