{ lib, ... }:
rec {
  USER = builtins.getEnv "USER";
  HOME = builtins.getEnv "HOME";
  _HOMENIX = ./home.nix;
  HOMENIX = (lib.trivial.throwIfNot (builtins.pathExists _HOMENIX) ''
  ${_HOMENIX} file must be present to build the configuration
  '') _HOMENIX;

  NIXSYSPATH = "/run/current-system/sw/bin";

  # github no reply email
  gh_noreply_email = "2169449+khsoh@users.noreply.github.com";

  ##### SSH related stuff #####
  _NIXIDPKFILE = "${HOME}/.ssh/nixid_ed25519";
  NIXIDPUBFILE = _NIXIDPKFILE + ".pub";
  USERPKFILE = "${HOME}/.ssh/id_ed25519";
  _USERPUBFILE = USERPKFILE + ".pub";

  ###### THE FOLLOWING ARE AUTOGENERATED FROM THE FILES ABOVE
  ###### DO NOT MODIFY - JUST CHANGE THE FILENAMES ABOVE IF NEEDED

  # It is possible to build system without a user private keyfile.
  # This is to build for systems running on a VM - so that the
  # chance of leaking the private key is minimized
  have_userpkfile = builtins.pathExists USERPKFILE;

  NIXIDPKFILE = (lib.trivial.throwIfNot (builtins.pathExists _NIXIDPKFILE) ''
    The NIXID ${_NIXIDPKFILE} ssh private key file is absent - this file must be present to build
    '') 
    ((lib.trivial.throwIfNot (builtins.pathExists NIXIDPUBFILE) ''
    The NIXID ${NIXIDPUBFILE} ssh public key file is absent - this file must be present to build
    '')
    _NIXIDPKFILE);

  USERPUBFILE = (lib.trivial.throwIfNot (builtins.pathExists _USERPUBFILE) ''
  The user ${_USERPUBFILE} ssh public key file is absent - this file must be present to build
  '') _USERPUBFILE;

  # SSH public keys - nixid_pubkey is used for testing in my VM environment
  #   - this is useful for testing in case we accidentally leak SSH key from test environment
  ssh_user_pubkey = builtins.concatStringsSep " " 
      (lib.lists.take 2 (builtins.filter (e: !(builtins.isList e)) 
        (builtins.split "[[:space:]\n]+" (builtins.readFile USERPUBFILE))));
  nixid_pubkey = builtins.concatStringsSep " " 
      (lib.lists.take 2 (builtins.filter (e: !(builtins.isList e)) 
        (builtins.split "[[:space:]\n]+" (builtins.readFile NIXIDPUBFILE))));
  ##### End of SSH related stuff #####
}
