#!/usr/bin/env zsh

echo "Copying SSH key..."

read "REMOTE_HOST?SSH destination in <user>@<ipaddr> form: "

DEFAULT_FILE="~/.ssh/nixid_ed25519"
read "TARGET_FILE?Target SSH Private key file name [$DEFAULT_FILE]: "
TARGET_FILE=${TARGET_FILE:-$DEFAULT_FILE}

DEFAULT_VAULT="Nix Bootstrap"
read "VAULT?Vault name [$DEFAULT_VAULT]: "
VAULT=${VAULT:-$DEFAULT_VAULT}

DEFAULT_ITEM="NIXID SSH Key"
read  "ITEM?Item name [$DEFAULT_ITEM]: "
ITEM=${ITEM:-$DEFAULT_ITEM}

ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $REMOTE_HOST "cat > $TARGET_FILE" < <(op read "op://${VAULT}/${ITEM}/private key?ssh-format=openssh")
