#!/bin/zsh


set -u
set -o pipefail

readonly ESC="$(tput sgr0)"
readonly BOLD="$(tput bold)"
readonly GREEN="$(tput setaf 2)"
readonly RED="$(tput setaf 1)"
readonly BLUE="$(tput setaf 4)"

# Script to perform configure tmux on Mac OS
#

{ # Prevent execution if this script was only partially downloaded
function print_arrow () {
    printf "${BOLD}${GREEN}"
    eval $(echo printf '"=%.0s"' {1..$SHLVL})
    printf "> $*${ESC}\n"
}

## Test to confirm nix has been installed
if [[ ! $(mount | grep -w "/nix") ]]; then
    printf "${BOLD}${RED}Error: Nix has not yet been installed - apps-configure script cannot be executed${ESC}\n"
    exit 1
fi

## Test to confirm nix-darwin has NOT yet been installed
if [[ ! $(nix --version 2>/dev/null) ]]; then
    ## Executed the startup scripts to ensure nix path is present
    [[ -f /etc/zshenv ]] && . /etc/zshenv
    . /etc/zprofile
    . /etc/zshrc
    if [[ ! $(nix --version 2>/dev/null) ]]; then
        printf "${BOLD}${RED}nix not yet installed - cannot execute apps-configure${ESC}\n"
        exit 1
    fi
fi

if [[ ! $(darwin-version --version 2>/dev/null) ]]; then
    [[ -f /etc/zshenv ]] && . /etc/zshenv
    . /etc/zprofile
    . /etc/zshrc
    if [[ ! $(darwin-version --version 2>/dev/null) ]]; then
        printf "${BOLD}${RED}nix-darwin not yet installed - cannot execute apps-configure${ESC}\n"
        exit 1
    fi
fi

## Note that ~/.config/tmux/tmux.conf was already linked via dostow.sh earlier in 
#  nixsys-setup
print_arrow "Configuring tmux"
tmux -c "~/.tmux/plugins/tpm/bindings/install_plugins" 2>/dev/null


## Configuring nvim

print_arrow "Configuring neovim"
~/.config/nvim/nvimupdate.sh -L
~/.config/nvim/nvimupdate.sh -M

printf "${BOLD}${BLUE}Restart a new terminal to start using Nix and nix-darwin${ESC}\n"

} # End of wrapping

