#!/bin/zsh


set -u
set -o pipefail

readonly ESC="$(tput sgr0)"
readonly BOLD="$(tput bold)"
readonly GREEN="$(tput setaf 2)"
readonly RED="$(tput setaf 1)"
readonly BLUE="$(tput setaf 4)"

# Script to perform installation of nix-darwin on MacOS
#

{ # Prevent execution if this script was only partially downloaded
function print_arrow () {
    printf "${BOLD}${GREEN}"
    eval $(echo printf '"=%.0s"' {1..$SHLVL})
    printf "> $*${ESC}\n"
}

oops() {
    echo "$0:" "$@" >&2
    exit 1
}

umask 0022

# Perform automated install
darwintmpDir="$(mktemp -d -t darwinautoinstalldir.XXXXXXXXX || \
          oops "Can't create temporary directory for downloading the nix-darwin install script")"

cleanup() {
    rm -rf "$darwintmpDir"
}
trap cleanup EXIT INT QUIT TERM

## Test to confirm nix has been installed
if [[ ! $(/sbin/mount | grep -w "/nix") ]]; then
    printf "${BOLD}${RED}Error: Nix has not yet been installed - darwin-autoinstall script cannot be executed${ESC}\n"
    exit 1
fi

## Test to confirm nix-darwin has NOT yet been installed
if [[ $(darwin-version --version 2>/dev/null) ]]; then
    printf "${BOLD}${RED}nix-darwin already installed${ESC}\n"
    exit 1
elif [[ ! $(nix --version 2>/dev/null) ]]; then
    ## Executed the startup scripts to ensure nix path is present
    . /etc/zprofile
    . /etc/zshrc
fi

if ! /opt/homebrew/bin/brew --version > /dev/null 2>&1 ; then
    echo "Installing Homebrew"
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

print_arrow "Downloading nix-darwin"
pushd $darwintmpDir
sudo -H nix-build https://github.com/nix-darwin/nix-darwin/archive/master.tar.gz -A darwin-rebuild

print_arrow "Starting a new sub-shell to configure nix-darwin"

# Trick to export print_arrow function to zsh sub-shell
func_print_arrow="$(typeset -f print_arrow)"
export func_print_arrow ESC BOLD RED GREEN BLUE
zsh -l <<EOF

eval "\$func_print_arrow"


sudo -H nix-channel --add https://github.com/nix-darwin/nix-darwin/archive/master.tar.gz darwin
sudo -H nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
## Install agenix channel
sudo -H nix-channel --add https://github.com/ryantm/agenix/archive/main.tar.gz agenix
sudo -H nix-channel --update

[ -f /etc/zshenv ] && . /etc/zshenv
[ -f /etc/zprofile ] && . /etc/zprofile
[ -f /etc/zshrc ] && . /etc/zshrc

sudo mkdir -p /etc/nix-channels
sudo chmod a+rx /etc/nix-channels
sudo cp /var/root/.nix-channels /etc/nix-channels/system-channels
sudo chmod a+r /etc/nix-channels/system-channels

print_arrow "Installing nix-darwin"

sudo -H $darwintmpDir/result/bin/darwin-rebuild switch -I darwin-config=$HOME/.config/nixpkgs/darwin/configuration.nix
EOF

popd


} # End of wrapping

